//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 08:30:26 AM EET 
//


package com.kobil.ssms.asm.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for appBundleParam complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="appBundleParam">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="asmUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="caPassPhrase" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="secureAsmUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "appBundleParam", propOrder = {
    "asmUrl",
    "caPassPhrase",
    "secureAsmUrl"
})
public class AppBundleParam {

    protected String asmUrl;
    protected String caPassPhrase;
    protected String secureAsmUrl;

    /**
     * Gets the value of the asmUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAsmUrl() {
        return asmUrl;
    }

    /**
     * Sets the value of the asmUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAsmUrl(String value) {
        this.asmUrl = value;
    }

    /**
     * Gets the value of the caPassPhrase property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCaPassPhrase() {
        return caPassPhrase;
    }

    /**
     * Sets the value of the caPassPhrase property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCaPassPhrase(String value) {
        this.caPassPhrase = value;
    }

    /**
     * Gets the value of the secureAsmUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSecureAsmUrl() {
        return secureAsmUrl;
    }

    /**
     * Sets the value of the secureAsmUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSecureAsmUrl(String value) {
        this.secureAsmUrl = value;
    }

}
