//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 08:30:26 AM EET 
//


package com.kobil.ssms.asm.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for createAppBundle complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="createAppBundle">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="appBundleParam" type="{http://ws.asm.ssms.kobil.com/}appBundleParam" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "createAppBundle", propOrder = {
    "appBundleParam"
})
public class CreateAppBundle {

    protected AppBundleParam appBundleParam;

    /**
     * Gets the value of the appBundleParam property.
     * 
     * @return
     *     possible object is
     *     {@link AppBundleParam }
     *     
     */
    public AppBundleParam getAppBundleParam() {
        return appBundleParam;
    }

    /**
     * Sets the value of the appBundleParam property.
     * 
     * @param value
     *     allowed object is
     *     {@link AppBundleParam }
     *     
     */
    public void setAppBundleParam(AppBundleParam value) {
        this.appBundleParam = value;
    }

}
