//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 08:30:26 AM EET 
//


package com.kobil.ssms.asm.ws;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for errorCodes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="errorCodes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="PERMISSION_DENIED"/>
 *     &lt;enumeration value="GENERAL_ERROR"/>
 *     &lt;enumeration value="USERID_INVALID"/>
 *     &lt;enumeration value="LOCK_REASON_INVALID"/>
 *     &lt;enumeration value="USER_NOT_FOUND"/>
 *     &lt;enumeration value="FILTER_INVALID"/>
 *     &lt;enumeration value="ACTIVATION_TIME_INVALID"/>
 *     &lt;enumeration value="ACTIVATION_TIME_HAS_EXPIRED"/>
 *     &lt;enumeration value="ISSUERDN_INVALID"/>
 *     &lt;enumeration value="SERIAL_NUMBER_INVALID"/>
 *     &lt;enumeration value="REQUESTED_CERTIFICATE_NOT_FOUND"/>
 *     &lt;enumeration value="ACTIVATION_CODE_INVALID"/>
 *     &lt;enumeration value="DEVICE_ID_INVALID"/>
 *     &lt;enumeration value="PARAMETER_INVALID"/>
 *     &lt;enumeration value="GROUP_NAME_INVALID"/>
 *     &lt;enumeration value="GROUP_NAME_NOT_START_WITH_AUTO_GROUP"/>
 *     &lt;enumeration value="GROUP_ALREADY_EXIST"/>
 *     &lt;enumeration value="GROUP_NOT_FOUND"/>
 *     &lt;enumeration value="SET_AUTO_GROUP_NOT_ALLOWED"/>
 *     &lt;enumeration value="USER_ALREADY_ASSIGNED_TO_GROUP"/>
 *     &lt;enumeration value="USER_ALREADY_UNASSIGNED_FROM_GROUP"/>
 *     &lt;enumeration value="STATISTIC_TYPE_INVALID"/>
 *     &lt;enumeration value="STATISTIC_PARAMETERS_INVALID"/>
 *     &lt;enumeration value="ACTIVATION_CODE_ALREADY_EXIST"/>
 *     &lt;enumeration value="ACTIVATION_INFO_INVALID"/>
 *     &lt;enumeration value="LANGUAGE_INVALID"/>
 *     &lt;enumeration value="CONTENTS_INVALID"/>
 *     &lt;enumeration value="USER_PIN_NOT_CONFIGURED"/>
 *     &lt;enumeration value="DEVICE_PARAMETER_INVALID"/>
 *     &lt;enumeration value="ACTIVATION_TIME_EXCEED_MAX_DURATION"/>
 *     &lt;enumeration value="ACTIVATION_CODE_LENGTH_INVALID"/>
 *     &lt;enumeration value="PARAMETER_MISSING"/>
 *     &lt;enumeration value="INVALID_CHARACTERS"/>
 *     &lt;enumeration value="APP_BUNDLE_PARAM_INVALID"/>
 *     &lt;enumeration value="INVALID_PIN_FOR_CA"/>
 *     &lt;enumeration value="INVALID_PORT"/>
 *     &lt;enumeration value="UNKNOWN_HOST"/>
 *     &lt;enumeration value="CONNECTION_FAILED"/>
 *     &lt;enumeration value="RETRIEVAL_CERT_CHAIN_FAILED"/>
 *     &lt;enumeration value="VERSION_PARAM_INVALID"/>
 *     &lt;enumeration value="SOFTWARE_TYPE_INVALID"/>
 *     &lt;enumeration value="CLIENT_TYPE_INVALID"/>
 *     &lt;enumeration value="DEVICE_TYPE_INVALID"/>
 *     &lt;enumeration value="APP_NAME_INVALID"/>
 *     &lt;enumeration value="VERSION_STR_INVALID"/>
 *     &lt;enumeration value="INSTALLER_INVALID"/>
 *     &lt;enumeration value="REQUESTED_VERSION_NOT_FOUND"/>
 *     &lt;enumeration value="VERSION_DELETION_PROHIBITED"/>
 *     &lt;enumeration value="VERSION_UPDATE_PARAM_INVALID"/>
 *     &lt;enumeration value="MANDATORY_FROM_INVALID"/>
 *     &lt;enumeration value="VERSION_UPDATE_WITH_NOT_NULL_VERSION_EXIST"/>
 *     &lt;enumeration value="VERSION_UPDATE_WITH_NULL_VERSION_EXIST"/>
 *     &lt;enumeration value="VERSION_UPDATE_NOT_FOUND"/>
 *     &lt;enumeration value="CERT_PROFILE_INVALID"/>
 *     &lt;enumeration value="CERTIFICATE_SIGNING_REQUEST_INVALID"/>
 *     &lt;enumeration value="CERT_CREATION_FAILED"/>
 *     &lt;enumeration value="CERTIFICATE_SIGNING_REQUEST_INVALID_SIGNATURE"/>
 *     &lt;enumeration value="DEVICE_NOT_ASSIGNED"/>
 *     &lt;enumeration value="DEVICE_NOT_FOUND"/>
 *     &lt;enumeration value="USER_IS_LOCKED"/>
 *     &lt;enumeration value="CERT_IS_LOCKED"/>
 *     &lt;enumeration value="CERT_IS_TEMPORARY_LOCKED"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "errorCodes")
@XmlEnum
public enum ErrorCodes {

    PERMISSION_DENIED,
    GENERAL_ERROR,
    USERID_INVALID,
    LOCK_REASON_INVALID,
    USER_NOT_FOUND,
    FILTER_INVALID,
    ACTIVATION_TIME_INVALID,
    ACTIVATION_TIME_HAS_EXPIRED,
    ISSUERDN_INVALID,
    SERIAL_NUMBER_INVALID,
    REQUESTED_CERTIFICATE_NOT_FOUND,
    ACTIVATION_CODE_INVALID,
    DEVICE_ID_INVALID,
    PARAMETER_INVALID,
    GROUP_NAME_INVALID,
    GROUP_NAME_NOT_START_WITH_AUTO_GROUP,
    GROUP_ALREADY_EXIST,
    GROUP_NOT_FOUND,
    SET_AUTO_GROUP_NOT_ALLOWED,
    USER_ALREADY_ASSIGNED_TO_GROUP,
    USER_ALREADY_UNASSIGNED_FROM_GROUP,
    STATISTIC_TYPE_INVALID,
    STATISTIC_PARAMETERS_INVALID,
    ACTIVATION_CODE_ALREADY_EXIST,
    ACTIVATION_INFO_INVALID,
    LANGUAGE_INVALID,
    CONTENTS_INVALID,
    USER_PIN_NOT_CONFIGURED,
    DEVICE_PARAMETER_INVALID,
    ACTIVATION_TIME_EXCEED_MAX_DURATION,
    ACTIVATION_CODE_LENGTH_INVALID,
    PARAMETER_MISSING,
    INVALID_CHARACTERS,
    APP_BUNDLE_PARAM_INVALID,
    INVALID_PIN_FOR_CA,
    INVALID_PORT,
    UNKNOWN_HOST,
    CONNECTION_FAILED,
    RETRIEVAL_CERT_CHAIN_FAILED,
    VERSION_PARAM_INVALID,
    SOFTWARE_TYPE_INVALID,
    CLIENT_TYPE_INVALID,
    DEVICE_TYPE_INVALID,
    APP_NAME_INVALID,
    VERSION_STR_INVALID,
    INSTALLER_INVALID,
    REQUESTED_VERSION_NOT_FOUND,
    VERSION_DELETION_PROHIBITED,
    VERSION_UPDATE_PARAM_INVALID,
    MANDATORY_FROM_INVALID,
    VERSION_UPDATE_WITH_NOT_NULL_VERSION_EXIST,
    VERSION_UPDATE_WITH_NULL_VERSION_EXIST,
    VERSION_UPDATE_NOT_FOUND,
    CERT_PROFILE_INVALID,
    CERTIFICATE_SIGNING_REQUEST_INVALID,
    CERT_CREATION_FAILED,
    CERTIFICATE_SIGNING_REQUEST_INVALID_SIGNATURE,
    DEVICE_NOT_ASSIGNED,
    DEVICE_NOT_FOUND,
    USER_IS_LOCKED,
    CERT_IS_LOCKED,
    CERT_IS_TEMPORARY_LOCKED;

    public String value() {
        return name();
    }

    public static ErrorCodes fromValue(String v) {
        return valueOf(v);
    }

}
