//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 08:30:26 AM EET 
//


package com.kobil.ssms.asm.ws;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for getStatistic complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="getStatistic">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="statisticTypeInfo" type="{http://ws.asm.ssms.kobil.com/}statisticTypeInfo" minOccurs="0"/>
 *         &lt;element name="statisticParameters" type="{http://www.w3.org/2001/XMLSchema}string" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getStatistic", propOrder = {
    "statisticTypeInfo",
    "statisticParameters"
})
public class GetStatistic {

    protected StatisticTypeInfo statisticTypeInfo;
    protected List<String> statisticParameters;

    /**
     * Gets the value of the statisticTypeInfo property.
     * 
     * @return
     *     possible object is
     *     {@link StatisticTypeInfo }
     *     
     */
    public StatisticTypeInfo getStatisticTypeInfo() {
        return statisticTypeInfo;
    }

    /**
     * Sets the value of the statisticTypeInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link StatisticTypeInfo }
     *     
     */
    public void setStatisticTypeInfo(StatisticTypeInfo value) {
        this.statisticTypeInfo = value;
    }

    /**
     * Gets the value of the statisticParameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the statisticParameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStatisticParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getStatisticParameters() {
        if (statisticParameters == null) {
            statisticParameters = new ArrayList<String>();
        }
        return this.statisticParameters;
    }

}
