//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 08:30:26 AM EET 
//


package com.kobil.ssms.asm.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.kobil.ssms.asm.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _EditVersionResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "editVersionResponse");
    private final static QName _AssignVersionUpdateResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "assignVersionUpdateResponse");
    private final static QName _LockDeviceByDeviceIdResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "lockDeviceByDeviceIdResponse");
    private final static QName _RemoveVersionChecksumResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "removeVersionChecksumResponse");
    private final static QName _UnlockDeviceByDeviceId_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "unlockDeviceByDeviceId");
    private final static QName _RemoveActivationCode_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "removeActivationCode");
    private final static QName _UnassignGroupFromUserResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "unassignGroupFromUserResponse");
    private final static QName _RemoveUserResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "removeUserResponse");
    private final static QName _RemoveDeviceExResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "removeDeviceExResponse");
    private final static QName _CopyPin_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "copyPin");
    private final static QName _GetDeviceMgtInfoResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getDeviceMgtInfoResponse");
    private final static QName _AddActivationCodeResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "addActivationCodeResponse");
    private final static QName _GetUserInfoResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getUserInfoResponse");
    private final static QName _CreateAppBundleResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "createAppBundleResponse");
    private final static QName _ModifyGroupResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "modifyGroupResponse");
    private final static QName _RemoveAllActivationCodes_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "removeAllActivationCodes");
    private final static QName _AssignGroupToUserResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "assignGroupToUserResponse");
    private final static QName _LockDevice_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "lockDevice");
    private final static QName _EditVersionUpdate_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "editVersionUpdate");
    private final static QName _GetNodes_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getNodes");
    private final static QName _GetCertificateByDeviceId_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getCertificateByDeviceId");
    private final static QName _UnassignVersionUpdateResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "unassignVersionUpdateResponse");
    private final static QName _CopyPinResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "copyPinResponse");
    private final static QName _GetGroups_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getGroups");
    private final static QName _RemoveActivationCodeResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "removeActivationCodeResponse");
    private final static QName _UnlockDeviceByDeviceIdResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "unlockDeviceByDeviceIdResponse");
    private final static QName _CreateActivationCode_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "createActivationCode");
    private final static QName _GetTextResourcesResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getTextResourcesResponse");
    private final static QName _GetUsers_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getUsers");
    private final static QName _RemoveUser_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "removeUser");
    private final static QName _StoreTextResourcesResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "storeTextResourcesResponse");
    private final static QName _UnlockUserResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "unlockUserResponse");
    private final static QName _AddActivationCode_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "addActivationCode");
    private final static QName _GetNodesResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getNodesResponse");
    private final static QName _ASMManagementWSFault_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "ASMManagementWSFault");
    private final static QName _RemoveVersion_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "removeVersion");
    private final static QName _RemoveVersionResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "removeVersionResponse");
    private final static QName _GetGroupsResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getGroupsResponse");
    private final static QName _AddUser_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "addUser");
    private final static QName _UnlockDevice_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "unlockDevice");
    private final static QName _CreateActivationCodeResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "createActivationCodeResponse");
    private final static QName _LockUserResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "lockUserResponse");
    private final static QName _GetDevicesForUser_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getDevicesForUser");
    private final static QName _GetDeviceMgtInfo_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getDeviceMgtInfo");
    private final static QName _CreateUserCertificate_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "createUserCertificate");
    private final static QName _GetUserGroupResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getUserGroupResponse");
    private final static QName _GetUsersResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getUsersResponse");
    private final static QName _GetDevicesForUserResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getDevicesForUserResponse");
    private final static QName _CreateAppBundle_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "createAppBundle");
    private final static QName _GetUserInfo_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getUserInfo");
    private final static QName _AddGroupResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "addGroupResponse");
    private final static QName _RemoveGroup_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "removeGroup");
    private final static QName _EditVersionUpdateResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "editVersionUpdateResponse");
    private final static QName _GetActivationCodes_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getActivationCodes");
    private final static QName _GetActivationCodesResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getActivationCodesResponse");
    private final static QName _GetStatisticResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getStatisticResponse");
    private final static QName _GetUserGroup_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getUserGroup");
    private final static QName _UnlockUser_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "unlockUser");
    private final static QName _CreateActivationCodeExResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "createActivationCodeExResponse");
    private final static QName _GetCertificateResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getCertificateResponse");
    private final static QName _RemoveGroupResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "removeGroupResponse");
    private final static QName _UnassignVersionUpdate_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "unassignVersionUpdate");
    private final static QName _RemoveVersionChecksum_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "removeVersionChecksum");
    private final static QName _GetCertificateByDeviceIdResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getCertificateByDeviceIdResponse");
    private final static QName _CreateUserCertificateResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "createUserCertificateResponse");
    private final static QName _ResetPin_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "resetPin");
    private final static QName _UnlockDeviceResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "unlockDeviceResponse");
    private final static QName _LockUser_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "lockUser");
    private final static QName _RemoveDeviceEx_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "removeDeviceEx");
    private final static QName _AddGroup_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "addGroup");
    private final static QName _CreateActivationCodeEx_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "createActivationCodeEx");
    private final static QName _GetReportingItemsResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getReportingItemsResponse");
    private final static QName _AddUserResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "addUserResponse");
    private final static QName _EditVersion_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "editVersion");
    private final static QName _StoreTextResources_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "storeTextResources");
    private final static QName _LockDeviceResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "lockDeviceResponse");
    private final static QName _SetPin_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "setPin");
    private final static QName _AssignGroupToUser_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "assignGroupToUser");
    private final static QName _AssignVersionUpdate_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "assignVersionUpdate");
    private final static QName _RemoveAllActivationCodesResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "removeAllActivationCodesResponse");
    private final static QName _SetPinResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "setPinResponse");
    private final static QName _GetCertificate_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getCertificate");
    private final static QName _AddVersionResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "addVersionResponse");
    private final static QName _ResetPinResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "resetPinResponse");
    private final static QName _RemoveDevice_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "removeDevice");
    private final static QName _GetTextResources_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getTextResources");
    private final static QName _LockDeviceByDeviceId_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "lockDeviceByDeviceId");
    private final static QName _RemoveDeviceByDeviceIdResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "removeDeviceByDeviceIdResponse");
    private final static QName _ModifyGroup_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "modifyGroup");
    private final static QName _AddVersion_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "addVersion");
    private final static QName _GetStatistic_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getStatistic");
    private final static QName _RemoveDeviceResponse_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "removeDeviceResponse");
    private final static QName _UnassignGroupFromUser_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "unassignGroupFromUser");
    private final static QName _GetReportingItems_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "getReportingItems");
    private final static QName _RemoveDeviceByDeviceId_QNAME = new QName("http://ws.asm.ssms.kobil.com/", "removeDeviceByDeviceId");
    private final static QName _GetCertificateResponseReturn_QNAME = new QName("", "return");
    private final static QName _StoreTextResourcesContents_QNAME = new QName("", "contents");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.kobil.ssms.asm.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetGroupsResponse }
     * 
     */
    public GetGroupsResponse createGetGroupsResponse() {
        return new GetGroupsResponse();
    }

    /**
     * Create an instance of {@link RemoveVersion }
     * 
     */
    public RemoveVersion createRemoveVersion() {
        return new RemoveVersion();
    }

    /**
     * Create an instance of {@link RemoveVersionResponse }
     * 
     */
    public RemoveVersionResponse createRemoveVersionResponse() {
        return new RemoveVersionResponse();
    }

    /**
     * Create an instance of {@link CreateActivationCodeResponse }
     * 
     */
    public CreateActivationCodeResponse createCreateActivationCodeResponse() {
        return new CreateActivationCodeResponse();
    }

    /**
     * Create an instance of {@link LockUserResponse }
     * 
     */
    public LockUserResponse createLockUserResponse() {
        return new LockUserResponse();
    }

    /**
     * Create an instance of {@link AddUser }
     * 
     */
    public AddUser createAddUser() {
        return new AddUser();
    }

    /**
     * Create an instance of {@link UnlockDevice }
     * 
     */
    public UnlockDevice createUnlockDevice() {
        return new UnlockDevice();
    }

    /**
     * Create an instance of {@link AddActivationCode }
     * 
     */
    public AddActivationCode createAddActivationCode() {
        return new AddActivationCode();
    }

    /**
     * Create an instance of {@link StoreTextResourcesResponse }
     * 
     */
    public StoreTextResourcesResponse createStoreTextResourcesResponse() {
        return new StoreTextResourcesResponse();
    }

    /**
     * Create an instance of {@link UnlockUserResponse }
     * 
     */
    public UnlockUserResponse createUnlockUserResponse() {
        return new UnlockUserResponse();
    }

    /**
     * Create an instance of {@link ASMManagementWSFault }
     * 
     */
    public ASMManagementWSFault createASMManagementWSFault() {
        return new ASMManagementWSFault();
    }

    /**
     * Create an instance of {@link GetNodesResponse }
     * 
     */
    public GetNodesResponse createGetNodesResponse() {
        return new GetNodesResponse();
    }

    /**
     * Create an instance of {@link RemoveActivationCodeResponse }
     * 
     */
    public RemoveActivationCodeResponse createRemoveActivationCodeResponse() {
        return new RemoveActivationCodeResponse();
    }

    /**
     * Create an instance of {@link RemoveUser }
     * 
     */
    public RemoveUser createRemoveUser() {
        return new RemoveUser();
    }

    /**
     * Create an instance of {@link CreateActivationCode }
     * 
     */
    public CreateActivationCode createCreateActivationCode() {
        return new CreateActivationCode();
    }

    /**
     * Create an instance of {@link GetTextResourcesResponse }
     * 
     */
    public GetTextResourcesResponse createGetTextResourcesResponse() {
        return new GetTextResourcesResponse();
    }

    /**
     * Create an instance of {@link GetUsers }
     * 
     */
    public GetUsers createGetUsers() {
        return new GetUsers();
    }

    /**
     * Create an instance of {@link UnlockDeviceByDeviceIdResponse }
     * 
     */
    public UnlockDeviceByDeviceIdResponse createUnlockDeviceByDeviceIdResponse() {
        return new UnlockDeviceByDeviceIdResponse();
    }

    /**
     * Create an instance of {@link UnassignVersionUpdateResponse }
     * 
     */
    public UnassignVersionUpdateResponse createUnassignVersionUpdateResponse() {
        return new UnassignVersionUpdateResponse();
    }

    /**
     * Create an instance of {@link GetCertificateByDeviceId }
     * 
     */
    public GetCertificateByDeviceId createGetCertificateByDeviceId() {
        return new GetCertificateByDeviceId();
    }

    /**
     * Create an instance of {@link GetGroups }
     * 
     */
    public GetGroups createGetGroups() {
        return new GetGroups();
    }

    /**
     * Create an instance of {@link CopyPinResponse }
     * 
     */
    public CopyPinResponse createCopyPinResponse() {
        return new CopyPinResponse();
    }

    /**
     * Create an instance of {@link EditVersionUpdate }
     * 
     */
    public EditVersionUpdate createEditVersionUpdate() {
        return new EditVersionUpdate();
    }

    /**
     * Create an instance of {@link GetNodes }
     * 
     */
    public GetNodes createGetNodes() {
        return new GetNodes();
    }

    /**
     * Create an instance of {@link AssignGroupToUserResponse }
     * 
     */
    public AssignGroupToUserResponse createAssignGroupToUserResponse() {
        return new AssignGroupToUserResponse();
    }

    /**
     * Create an instance of {@link LockDevice }
     * 
     */
    public LockDevice createLockDevice() {
        return new LockDevice();
    }

    /**
     * Create an instance of {@link RemoveAllActivationCodes }
     * 
     */
    public RemoveAllActivationCodes createRemoveAllActivationCodes() {
        return new RemoveAllActivationCodes();
    }

    /**
     * Create an instance of {@link CreateAppBundleResponse }
     * 
     */
    public CreateAppBundleResponse createCreateAppBundleResponse() {
        return new CreateAppBundleResponse();
    }

    /**
     * Create an instance of {@link GetUserInfoResponse }
     * 
     */
    public GetUserInfoResponse createGetUserInfoResponse() {
        return new GetUserInfoResponse();
    }

    /**
     * Create an instance of {@link AddActivationCodeResponse }
     * 
     */
    public AddActivationCodeResponse createAddActivationCodeResponse() {
        return new AddActivationCodeResponse();
    }

    /**
     * Create an instance of {@link ModifyGroupResponse }
     * 
     */
    public ModifyGroupResponse createModifyGroupResponse() {
        return new ModifyGroupResponse();
    }

    /**
     * Create an instance of {@link RemoveUserResponse }
     * 
     */
    public RemoveUserResponse createRemoveUserResponse() {
        return new RemoveUserResponse();
    }

    /**
     * Create an instance of {@link GetDeviceMgtInfoResponse }
     * 
     */
    public GetDeviceMgtInfoResponse createGetDeviceMgtInfoResponse() {
        return new GetDeviceMgtInfoResponse();
    }

    /**
     * Create an instance of {@link CopyPin }
     * 
     */
    public CopyPin createCopyPin() {
        return new CopyPin();
    }

    /**
     * Create an instance of {@link RemoveDeviceExResponse }
     * 
     */
    public RemoveDeviceExResponse createRemoveDeviceExResponse() {
        return new RemoveDeviceExResponse();
    }

    /**
     * Create an instance of {@link AssignVersionUpdateResponse }
     * 
     */
    public AssignVersionUpdateResponse createAssignVersionUpdateResponse() {
        return new AssignVersionUpdateResponse();
    }

    /**
     * Create an instance of {@link EditVersionResponse }
     * 
     */
    public EditVersionResponse createEditVersionResponse() {
        return new EditVersionResponse();
    }

    /**
     * Create an instance of {@link UnassignGroupFromUserResponse }
     * 
     */
    public UnassignGroupFromUserResponse createUnassignGroupFromUserResponse() {
        return new UnassignGroupFromUserResponse();
    }

    /**
     * Create an instance of {@link RemoveActivationCode }
     * 
     */
    public RemoveActivationCode createRemoveActivationCode() {
        return new RemoveActivationCode();
    }

    /**
     * Create an instance of {@link LockDeviceByDeviceIdResponse }
     * 
     */
    public LockDeviceByDeviceIdResponse createLockDeviceByDeviceIdResponse() {
        return new LockDeviceByDeviceIdResponse();
    }

    /**
     * Create an instance of {@link RemoveVersionChecksumResponse }
     * 
     */
    public RemoveVersionChecksumResponse createRemoveVersionChecksumResponse() {
        return new RemoveVersionChecksumResponse();
    }

    /**
     * Create an instance of {@link UnlockDeviceByDeviceId }
     * 
     */
    public UnlockDeviceByDeviceId createUnlockDeviceByDeviceId() {
        return new UnlockDeviceByDeviceId();
    }

    /**
     * Create an instance of {@link GetReportingItems }
     * 
     */
    public GetReportingItems createGetReportingItems() {
        return new GetReportingItems();
    }

    /**
     * Create an instance of {@link RemoveDeviceByDeviceId }
     * 
     */
    public RemoveDeviceByDeviceId createRemoveDeviceByDeviceId() {
        return new RemoveDeviceByDeviceId();
    }

    /**
     * Create an instance of {@link AddVersion }
     * 
     */
    public AddVersion createAddVersion() {
        return new AddVersion();
    }

    /**
     * Create an instance of {@link GetStatistic }
     * 
     */
    public GetStatistic createGetStatistic() {
        return new GetStatistic();
    }

    /**
     * Create an instance of {@link RemoveDeviceResponse }
     * 
     */
    public RemoveDeviceResponse createRemoveDeviceResponse() {
        return new RemoveDeviceResponse();
    }

    /**
     * Create an instance of {@link UnassignGroupFromUser }
     * 
     */
    public UnassignGroupFromUser createUnassignGroupFromUser() {
        return new UnassignGroupFromUser();
    }

    /**
     * Create an instance of {@link ModifyGroup }
     * 
     */
    public ModifyGroup createModifyGroup() {
        return new ModifyGroup();
    }

    /**
     * Create an instance of {@link GetTextResources }
     * 
     */
    public GetTextResources createGetTextResources() {
        return new GetTextResources();
    }

    /**
     * Create an instance of {@link LockDeviceByDeviceId }
     * 
     */
    public LockDeviceByDeviceId createLockDeviceByDeviceId() {
        return new LockDeviceByDeviceId();
    }

    /**
     * Create an instance of {@link RemoveDeviceByDeviceIdResponse }
     * 
     */
    public RemoveDeviceByDeviceIdResponse createRemoveDeviceByDeviceIdResponse() {
        return new RemoveDeviceByDeviceIdResponse();
    }

    /**
     * Create an instance of {@link RemoveDevice }
     * 
     */
    public RemoveDevice createRemoveDevice() {
        return new RemoveDevice();
    }

    /**
     * Create an instance of {@link AddVersionResponse }
     * 
     */
    public AddVersionResponse createAddVersionResponse() {
        return new AddVersionResponse();
    }

    /**
     * Create an instance of {@link ResetPinResponse }
     * 
     */
    public ResetPinResponse createResetPinResponse() {
        return new ResetPinResponse();
    }

    /**
     * Create an instance of {@link AssignGroupToUser }
     * 
     */
    public AssignGroupToUser createAssignGroupToUser() {
        return new AssignGroupToUser();
    }

    /**
     * Create an instance of {@link LockDeviceResponse }
     * 
     */
    public LockDeviceResponse createLockDeviceResponse() {
        return new LockDeviceResponse();
    }

    /**
     * Create an instance of {@link SetPin }
     * 
     */
    public SetPin createSetPin() {
        return new SetPin();
    }

    /**
     * Create an instance of {@link StoreTextResources }
     * 
     */
    public StoreTextResources createStoreTextResources() {
        return new StoreTextResources();
    }

    /**
     * Create an instance of {@link GetCertificate }
     * 
     */
    public GetCertificate createGetCertificate() {
        return new GetCertificate();
    }

    /**
     * Create an instance of {@link SetPinResponse }
     * 
     */
    public SetPinResponse createSetPinResponse() {
        return new SetPinResponse();
    }

    /**
     * Create an instance of {@link AssignVersionUpdate }
     * 
     */
    public AssignVersionUpdate createAssignVersionUpdate() {
        return new AssignVersionUpdate();
    }

    /**
     * Create an instance of {@link RemoveAllActivationCodesResponse }
     * 
     */
    public RemoveAllActivationCodesResponse createRemoveAllActivationCodesResponse() {
        return new RemoveAllActivationCodesResponse();
    }

    /**
     * Create an instance of {@link LockUser }
     * 
     */
    public LockUser createLockUser() {
        return new LockUser();
    }

    /**
     * Create an instance of {@link ResetPin }
     * 
     */
    public ResetPin createResetPin() {
        return new ResetPin();
    }

    /**
     * Create an instance of {@link UnlockDeviceResponse }
     * 
     */
    public UnlockDeviceResponse createUnlockDeviceResponse() {
        return new UnlockDeviceResponse();
    }

    /**
     * Create an instance of {@link AddUserResponse }
     * 
     */
    public AddUserResponse createAddUserResponse() {
        return new AddUserResponse();
    }

    /**
     * Create an instance of {@link EditVersion }
     * 
     */
    public EditVersion createEditVersion() {
        return new EditVersion();
    }

    /**
     * Create an instance of {@link AddGroup }
     * 
     */
    public AddGroup createAddGroup() {
        return new AddGroup();
    }

    /**
     * Create an instance of {@link CreateActivationCodeEx }
     * 
     */
    public CreateActivationCodeEx createCreateActivationCodeEx() {
        return new CreateActivationCodeEx();
    }

    /**
     * Create an instance of {@link GetReportingItemsResponse }
     * 
     */
    public GetReportingItemsResponse createGetReportingItemsResponse() {
        return new GetReportingItemsResponse();
    }

    /**
     * Create an instance of {@link RemoveDeviceEx }
     * 
     */
    public RemoveDeviceEx createRemoveDeviceEx() {
        return new RemoveDeviceEx();
    }

    /**
     * Create an instance of {@link CreateUserCertificateResponse }
     * 
     */
    public CreateUserCertificateResponse createCreateUserCertificateResponse() {
        return new CreateUserCertificateResponse();
    }

    /**
     * Create an instance of {@link GetCertificateByDeviceIdResponse }
     * 
     */
    public GetCertificateByDeviceIdResponse createGetCertificateByDeviceIdResponse() {
        return new GetCertificateByDeviceIdResponse();
    }

    /**
     * Create an instance of {@link CreateActivationCodeExResponse }
     * 
     */
    public CreateActivationCodeExResponse createCreateActivationCodeExResponse() {
        return new CreateActivationCodeExResponse();
    }

    /**
     * Create an instance of {@link GetStatisticResponse }
     * 
     */
    public GetStatisticResponse createGetStatisticResponse() {
        return new GetStatisticResponse();
    }

    /**
     * Create an instance of {@link GetUserGroup }
     * 
     */
    public GetUserGroup createGetUserGroup() {
        return new GetUserGroup();
    }

    /**
     * Create an instance of {@link UnlockUser }
     * 
     */
    public UnlockUser createUnlockUser() {
        return new UnlockUser();
    }

    /**
     * Create an instance of {@link RemoveVersionChecksum }
     * 
     */
    public RemoveVersionChecksum createRemoveVersionChecksum() {
        return new RemoveVersionChecksum();
    }

    /**
     * Create an instance of {@link RemoveGroupResponse }
     * 
     */
    public RemoveGroupResponse createRemoveGroupResponse() {
        return new RemoveGroupResponse();
    }

    /**
     * Create an instance of {@link UnassignVersionUpdate }
     * 
     */
    public UnassignVersionUpdate createUnassignVersionUpdate() {
        return new UnassignVersionUpdate();
    }

    /**
     * Create an instance of {@link GetCertificateResponse }
     * 
     */
    public GetCertificateResponse createGetCertificateResponse() {
        return new GetCertificateResponse();
    }

    /**
     * Create an instance of {@link AddGroupResponse }
     * 
     */
    public AddGroupResponse createAddGroupResponse() {
        return new AddGroupResponse();
    }

    /**
     * Create an instance of {@link GetActivationCodes }
     * 
     */
    public GetActivationCodes createGetActivationCodes() {
        return new GetActivationCodes();
    }

    /**
     * Create an instance of {@link GetActivationCodesResponse }
     * 
     */
    public GetActivationCodesResponse createGetActivationCodesResponse() {
        return new GetActivationCodesResponse();
    }

    /**
     * Create an instance of {@link EditVersionUpdateResponse }
     * 
     */
    public EditVersionUpdateResponse createEditVersionUpdateResponse() {
        return new EditVersionUpdateResponse();
    }

    /**
     * Create an instance of {@link RemoveGroup }
     * 
     */
    public RemoveGroup createRemoveGroup() {
        return new RemoveGroup();
    }

    /**
     * Create an instance of {@link GetDeviceMgtInfo }
     * 
     */
    public GetDeviceMgtInfo createGetDeviceMgtInfo() {
        return new GetDeviceMgtInfo();
    }

    /**
     * Create an instance of {@link GetDevicesForUser }
     * 
     */
    public GetDevicesForUser createGetDevicesForUser() {
        return new GetDevicesForUser();
    }

    /**
     * Create an instance of {@link CreateAppBundle }
     * 
     */
    public CreateAppBundle createCreateAppBundle() {
        return new CreateAppBundle();
    }

    /**
     * Create an instance of {@link GetUserInfo }
     * 
     */
    public GetUserInfo createGetUserInfo() {
        return new GetUserInfo();
    }

    /**
     * Create an instance of {@link GetDevicesForUserResponse }
     * 
     */
    public GetDevicesForUserResponse createGetDevicesForUserResponse() {
        return new GetDevicesForUserResponse();
    }

    /**
     * Create an instance of {@link CreateUserCertificate }
     * 
     */
    public CreateUserCertificate createCreateUserCertificate() {
        return new CreateUserCertificate();
    }

    /**
     * Create an instance of {@link GetUserGroupResponse }
     * 
     */
    public GetUserGroupResponse createGetUserGroupResponse() {
        return new GetUserGroupResponse();
    }

    /**
     * Create an instance of {@link GetUsersResponse }
     * 
     */
    public GetUsersResponse createGetUsersResponse() {
        return new GetUsersResponse();
    }

    /**
     * Create an instance of {@link UserInfo }
     * 
     */
    public UserInfo createUserInfo() {
        return new UserInfo();
    }

    /**
     * Create an instance of {@link VersionUpdateParam }
     * 
     */
    public VersionUpdateParam createVersionUpdateParam() {
        return new VersionUpdateParam();
    }

    /**
     * Create an instance of {@link SsmsNode }
     * 
     */
    public SsmsNode createSsmsNode() {
        return new SsmsNode();
    }

    /**
     * Create an instance of {@link ReportingInfo }
     * 
     */
    public ReportingInfo createReportingInfo() {
        return new ReportingInfo();
    }

    /**
     * Create an instance of {@link AppBundleParam }
     * 
     */
    public AppBundleParam createAppBundleParam() {
        return new AppBundleParam();
    }

    /**
     * Create an instance of {@link ActivationCodeParam }
     * 
     */
    public ActivationCodeParam createActivationCodeParam() {
        return new ActivationCodeParam();
    }

    /**
     * Create an instance of {@link AsmDeviceMgtInfo }
     * 
     */
    public AsmDeviceMgtInfo createAsmDeviceMgtInfo() {
        return new AsmDeviceMgtInfo();
    }

    /**
     * Create an instance of {@link VersionParam }
     * 
     */
    public VersionParam createVersionParam() {
        return new VersionParam();
    }

    /**
     * Create an instance of {@link ReportingInfoItem }
     * 
     */
    public ReportingInfoItem createReportingInfoItem() {
        return new ReportingInfoItem();
    }

    /**
     * Create an instance of {@link AsmActivationCodeInfo }
     * 
     */
    public AsmActivationCodeInfo createAsmActivationCodeInfo() {
        return new AsmActivationCodeInfo();
    }

    /**
     * Create an instance of {@link ReportingFilter }
     * 
     */
    public ReportingFilter createReportingFilter() {
        return new ReportingFilter();
    }

    /**
     * Create an instance of {@link DeviceParam }
     * 
     */
    public DeviceParam createDeviceParam() {
        return new DeviceParam();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EditVersionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "editVersionResponse")
    public JAXBElement<EditVersionResponse> createEditVersionResponse(EditVersionResponse value) {
        return new JAXBElement<EditVersionResponse>(_EditVersionResponse_QNAME, EditVersionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AssignVersionUpdateResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "assignVersionUpdateResponse")
    public JAXBElement<AssignVersionUpdateResponse> createAssignVersionUpdateResponse(AssignVersionUpdateResponse value) {
        return new JAXBElement<AssignVersionUpdateResponse>(_AssignVersionUpdateResponse_QNAME, AssignVersionUpdateResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LockDeviceByDeviceIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "lockDeviceByDeviceIdResponse")
    public JAXBElement<LockDeviceByDeviceIdResponse> createLockDeviceByDeviceIdResponse(LockDeviceByDeviceIdResponse value) {
        return new JAXBElement<LockDeviceByDeviceIdResponse>(_LockDeviceByDeviceIdResponse_QNAME, LockDeviceByDeviceIdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveVersionChecksumResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "removeVersionChecksumResponse")
    public JAXBElement<RemoveVersionChecksumResponse> createRemoveVersionChecksumResponse(RemoveVersionChecksumResponse value) {
        return new JAXBElement<RemoveVersionChecksumResponse>(_RemoveVersionChecksumResponse_QNAME, RemoveVersionChecksumResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnlockDeviceByDeviceId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "unlockDeviceByDeviceId")
    public JAXBElement<UnlockDeviceByDeviceId> createUnlockDeviceByDeviceId(UnlockDeviceByDeviceId value) {
        return new JAXBElement<UnlockDeviceByDeviceId>(_UnlockDeviceByDeviceId_QNAME, UnlockDeviceByDeviceId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveActivationCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "removeActivationCode")
    public JAXBElement<RemoveActivationCode> createRemoveActivationCode(RemoveActivationCode value) {
        return new JAXBElement<RemoveActivationCode>(_RemoveActivationCode_QNAME, RemoveActivationCode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnassignGroupFromUserResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "unassignGroupFromUserResponse")
    public JAXBElement<UnassignGroupFromUserResponse> createUnassignGroupFromUserResponse(UnassignGroupFromUserResponse value) {
        return new JAXBElement<UnassignGroupFromUserResponse>(_UnassignGroupFromUserResponse_QNAME, UnassignGroupFromUserResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveUserResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "removeUserResponse")
    public JAXBElement<RemoveUserResponse> createRemoveUserResponse(RemoveUserResponse value) {
        return new JAXBElement<RemoveUserResponse>(_RemoveUserResponse_QNAME, RemoveUserResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveDeviceExResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "removeDeviceExResponse")
    public JAXBElement<RemoveDeviceExResponse> createRemoveDeviceExResponse(RemoveDeviceExResponse value) {
        return new JAXBElement<RemoveDeviceExResponse>(_RemoveDeviceExResponse_QNAME, RemoveDeviceExResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CopyPin }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "copyPin")
    public JAXBElement<CopyPin> createCopyPin(CopyPin value) {
        return new JAXBElement<CopyPin>(_CopyPin_QNAME, CopyPin.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDeviceMgtInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getDeviceMgtInfoResponse")
    public JAXBElement<GetDeviceMgtInfoResponse> createGetDeviceMgtInfoResponse(GetDeviceMgtInfoResponse value) {
        return new JAXBElement<GetDeviceMgtInfoResponse>(_GetDeviceMgtInfoResponse_QNAME, GetDeviceMgtInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddActivationCodeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "addActivationCodeResponse")
    public JAXBElement<AddActivationCodeResponse> createAddActivationCodeResponse(AddActivationCodeResponse value) {
        return new JAXBElement<AddActivationCodeResponse>(_AddActivationCodeResponse_QNAME, AddActivationCodeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUserInfoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getUserInfoResponse")
    public JAXBElement<GetUserInfoResponse> createGetUserInfoResponse(GetUserInfoResponse value) {
        return new JAXBElement<GetUserInfoResponse>(_GetUserInfoResponse_QNAME, GetUserInfoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateAppBundleResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "createAppBundleResponse")
    public JAXBElement<CreateAppBundleResponse> createCreateAppBundleResponse(CreateAppBundleResponse value) {
        return new JAXBElement<CreateAppBundleResponse>(_CreateAppBundleResponse_QNAME, CreateAppBundleResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModifyGroupResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "modifyGroupResponse")
    public JAXBElement<ModifyGroupResponse> createModifyGroupResponse(ModifyGroupResponse value) {
        return new JAXBElement<ModifyGroupResponse>(_ModifyGroupResponse_QNAME, ModifyGroupResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveAllActivationCodes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "removeAllActivationCodes")
    public JAXBElement<RemoveAllActivationCodes> createRemoveAllActivationCodes(RemoveAllActivationCodes value) {
        return new JAXBElement<RemoveAllActivationCodes>(_RemoveAllActivationCodes_QNAME, RemoveAllActivationCodes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AssignGroupToUserResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "assignGroupToUserResponse")
    public JAXBElement<AssignGroupToUserResponse> createAssignGroupToUserResponse(AssignGroupToUserResponse value) {
        return new JAXBElement<AssignGroupToUserResponse>(_AssignGroupToUserResponse_QNAME, AssignGroupToUserResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LockDevice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "lockDevice")
    public JAXBElement<LockDevice> createLockDevice(LockDevice value) {
        return new JAXBElement<LockDevice>(_LockDevice_QNAME, LockDevice.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EditVersionUpdate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "editVersionUpdate")
    public JAXBElement<EditVersionUpdate> createEditVersionUpdate(EditVersionUpdate value) {
        return new JAXBElement<EditVersionUpdate>(_EditVersionUpdate_QNAME, EditVersionUpdate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetNodes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getNodes")
    public JAXBElement<GetNodes> createGetNodes(GetNodes value) {
        return new JAXBElement<GetNodes>(_GetNodes_QNAME, GetNodes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCertificateByDeviceId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getCertificateByDeviceId")
    public JAXBElement<GetCertificateByDeviceId> createGetCertificateByDeviceId(GetCertificateByDeviceId value) {
        return new JAXBElement<GetCertificateByDeviceId>(_GetCertificateByDeviceId_QNAME, GetCertificateByDeviceId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnassignVersionUpdateResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "unassignVersionUpdateResponse")
    public JAXBElement<UnassignVersionUpdateResponse> createUnassignVersionUpdateResponse(UnassignVersionUpdateResponse value) {
        return new JAXBElement<UnassignVersionUpdateResponse>(_UnassignVersionUpdateResponse_QNAME, UnassignVersionUpdateResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CopyPinResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "copyPinResponse")
    public JAXBElement<CopyPinResponse> createCopyPinResponse(CopyPinResponse value) {
        return new JAXBElement<CopyPinResponse>(_CopyPinResponse_QNAME, CopyPinResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetGroups }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getGroups")
    public JAXBElement<GetGroups> createGetGroups(GetGroups value) {
        return new JAXBElement<GetGroups>(_GetGroups_QNAME, GetGroups.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveActivationCodeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "removeActivationCodeResponse")
    public JAXBElement<RemoveActivationCodeResponse> createRemoveActivationCodeResponse(RemoveActivationCodeResponse value) {
        return new JAXBElement<RemoveActivationCodeResponse>(_RemoveActivationCodeResponse_QNAME, RemoveActivationCodeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnlockDeviceByDeviceIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "unlockDeviceByDeviceIdResponse")
    public JAXBElement<UnlockDeviceByDeviceIdResponse> createUnlockDeviceByDeviceIdResponse(UnlockDeviceByDeviceIdResponse value) {
        return new JAXBElement<UnlockDeviceByDeviceIdResponse>(_UnlockDeviceByDeviceIdResponse_QNAME, UnlockDeviceByDeviceIdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateActivationCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "createActivationCode")
    public JAXBElement<CreateActivationCode> createCreateActivationCode(CreateActivationCode value) {
        return new JAXBElement<CreateActivationCode>(_CreateActivationCode_QNAME, CreateActivationCode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTextResourcesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getTextResourcesResponse")
    public JAXBElement<GetTextResourcesResponse> createGetTextResourcesResponse(GetTextResourcesResponse value) {
        return new JAXBElement<GetTextResourcesResponse>(_GetTextResourcesResponse_QNAME, GetTextResourcesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUsers }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getUsers")
    public JAXBElement<GetUsers> createGetUsers(GetUsers value) {
        return new JAXBElement<GetUsers>(_GetUsers_QNAME, GetUsers.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveUser }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "removeUser")
    public JAXBElement<RemoveUser> createRemoveUser(RemoveUser value) {
        return new JAXBElement<RemoveUser>(_RemoveUser_QNAME, RemoveUser.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StoreTextResourcesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "storeTextResourcesResponse")
    public JAXBElement<StoreTextResourcesResponse> createStoreTextResourcesResponse(StoreTextResourcesResponse value) {
        return new JAXBElement<StoreTextResourcesResponse>(_StoreTextResourcesResponse_QNAME, StoreTextResourcesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnlockUserResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "unlockUserResponse")
    public JAXBElement<UnlockUserResponse> createUnlockUserResponse(UnlockUserResponse value) {
        return new JAXBElement<UnlockUserResponse>(_UnlockUserResponse_QNAME, UnlockUserResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddActivationCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "addActivationCode")
    public JAXBElement<AddActivationCode> createAddActivationCode(AddActivationCode value) {
        return new JAXBElement<AddActivationCode>(_AddActivationCode_QNAME, AddActivationCode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetNodesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getNodesResponse")
    public JAXBElement<GetNodesResponse> createGetNodesResponse(GetNodesResponse value) {
        return new JAXBElement<GetNodesResponse>(_GetNodesResponse_QNAME, GetNodesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ASMManagementWSFault }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "ASMManagementWSFault")
    public JAXBElement<ASMManagementWSFault> createASMManagementWSFault(ASMManagementWSFault value) {
        return new JAXBElement<ASMManagementWSFault>(_ASMManagementWSFault_QNAME, ASMManagementWSFault.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveVersion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "removeVersion")
    public JAXBElement<RemoveVersion> createRemoveVersion(RemoveVersion value) {
        return new JAXBElement<RemoveVersion>(_RemoveVersion_QNAME, RemoveVersion.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveVersionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "removeVersionResponse")
    public JAXBElement<RemoveVersionResponse> createRemoveVersionResponse(RemoveVersionResponse value) {
        return new JAXBElement<RemoveVersionResponse>(_RemoveVersionResponse_QNAME, RemoveVersionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetGroupsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getGroupsResponse")
    public JAXBElement<GetGroupsResponse> createGetGroupsResponse(GetGroupsResponse value) {
        return new JAXBElement<GetGroupsResponse>(_GetGroupsResponse_QNAME, GetGroupsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddUser }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "addUser")
    public JAXBElement<AddUser> createAddUser(AddUser value) {
        return new JAXBElement<AddUser>(_AddUser_QNAME, AddUser.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnlockDevice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "unlockDevice")
    public JAXBElement<UnlockDevice> createUnlockDevice(UnlockDevice value) {
        return new JAXBElement<UnlockDevice>(_UnlockDevice_QNAME, UnlockDevice.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateActivationCodeResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "createActivationCodeResponse")
    public JAXBElement<CreateActivationCodeResponse> createCreateActivationCodeResponse(CreateActivationCodeResponse value) {
        return new JAXBElement<CreateActivationCodeResponse>(_CreateActivationCodeResponse_QNAME, CreateActivationCodeResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LockUserResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "lockUserResponse")
    public JAXBElement<LockUserResponse> createLockUserResponse(LockUserResponse value) {
        return new JAXBElement<LockUserResponse>(_LockUserResponse_QNAME, LockUserResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDevicesForUser }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getDevicesForUser")
    public JAXBElement<GetDevicesForUser> createGetDevicesForUser(GetDevicesForUser value) {
        return new JAXBElement<GetDevicesForUser>(_GetDevicesForUser_QNAME, GetDevicesForUser.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDeviceMgtInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getDeviceMgtInfo")
    public JAXBElement<GetDeviceMgtInfo> createGetDeviceMgtInfo(GetDeviceMgtInfo value) {
        return new JAXBElement<GetDeviceMgtInfo>(_GetDeviceMgtInfo_QNAME, GetDeviceMgtInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateUserCertificate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "createUserCertificate")
    public JAXBElement<CreateUserCertificate> createCreateUserCertificate(CreateUserCertificate value) {
        return new JAXBElement<CreateUserCertificate>(_CreateUserCertificate_QNAME, CreateUserCertificate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUserGroupResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getUserGroupResponse")
    public JAXBElement<GetUserGroupResponse> createGetUserGroupResponse(GetUserGroupResponse value) {
        return new JAXBElement<GetUserGroupResponse>(_GetUserGroupResponse_QNAME, GetUserGroupResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUsersResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getUsersResponse")
    public JAXBElement<GetUsersResponse> createGetUsersResponse(GetUsersResponse value) {
        return new JAXBElement<GetUsersResponse>(_GetUsersResponse_QNAME, GetUsersResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetDevicesForUserResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getDevicesForUserResponse")
    public JAXBElement<GetDevicesForUserResponse> createGetDevicesForUserResponse(GetDevicesForUserResponse value) {
        return new JAXBElement<GetDevicesForUserResponse>(_GetDevicesForUserResponse_QNAME, GetDevicesForUserResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateAppBundle }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "createAppBundle")
    public JAXBElement<CreateAppBundle> createCreateAppBundle(CreateAppBundle value) {
        return new JAXBElement<CreateAppBundle>(_CreateAppBundle_QNAME, CreateAppBundle.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUserInfo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getUserInfo")
    public JAXBElement<GetUserInfo> createGetUserInfo(GetUserInfo value) {
        return new JAXBElement<GetUserInfo>(_GetUserInfo_QNAME, GetUserInfo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddGroupResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "addGroupResponse")
    public JAXBElement<AddGroupResponse> createAddGroupResponse(AddGroupResponse value) {
        return new JAXBElement<AddGroupResponse>(_AddGroupResponse_QNAME, AddGroupResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveGroup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "removeGroup")
    public JAXBElement<RemoveGroup> createRemoveGroup(RemoveGroup value) {
        return new JAXBElement<RemoveGroup>(_RemoveGroup_QNAME, RemoveGroup.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EditVersionUpdateResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "editVersionUpdateResponse")
    public JAXBElement<EditVersionUpdateResponse> createEditVersionUpdateResponse(EditVersionUpdateResponse value) {
        return new JAXBElement<EditVersionUpdateResponse>(_EditVersionUpdateResponse_QNAME, EditVersionUpdateResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetActivationCodes }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getActivationCodes")
    public JAXBElement<GetActivationCodes> createGetActivationCodes(GetActivationCodes value) {
        return new JAXBElement<GetActivationCodes>(_GetActivationCodes_QNAME, GetActivationCodes.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetActivationCodesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getActivationCodesResponse")
    public JAXBElement<GetActivationCodesResponse> createGetActivationCodesResponse(GetActivationCodesResponse value) {
        return new JAXBElement<GetActivationCodesResponse>(_GetActivationCodesResponse_QNAME, GetActivationCodesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStatisticResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getStatisticResponse")
    public JAXBElement<GetStatisticResponse> createGetStatisticResponse(GetStatisticResponse value) {
        return new JAXBElement<GetStatisticResponse>(_GetStatisticResponse_QNAME, GetStatisticResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetUserGroup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getUserGroup")
    public JAXBElement<GetUserGroup> createGetUserGroup(GetUserGroup value) {
        return new JAXBElement<GetUserGroup>(_GetUserGroup_QNAME, GetUserGroup.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnlockUser }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "unlockUser")
    public JAXBElement<UnlockUser> createUnlockUser(UnlockUser value) {
        return new JAXBElement<UnlockUser>(_UnlockUser_QNAME, UnlockUser.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateActivationCodeExResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "createActivationCodeExResponse")
    public JAXBElement<CreateActivationCodeExResponse> createCreateActivationCodeExResponse(CreateActivationCodeExResponse value) {
        return new JAXBElement<CreateActivationCodeExResponse>(_CreateActivationCodeExResponse_QNAME, CreateActivationCodeExResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCertificateResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getCertificateResponse")
    public JAXBElement<GetCertificateResponse> createGetCertificateResponse(GetCertificateResponse value) {
        return new JAXBElement<GetCertificateResponse>(_GetCertificateResponse_QNAME, GetCertificateResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveGroupResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "removeGroupResponse")
    public JAXBElement<RemoveGroupResponse> createRemoveGroupResponse(RemoveGroupResponse value) {
        return new JAXBElement<RemoveGroupResponse>(_RemoveGroupResponse_QNAME, RemoveGroupResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnassignVersionUpdate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "unassignVersionUpdate")
    public JAXBElement<UnassignVersionUpdate> createUnassignVersionUpdate(UnassignVersionUpdate value) {
        return new JAXBElement<UnassignVersionUpdate>(_UnassignVersionUpdate_QNAME, UnassignVersionUpdate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveVersionChecksum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "removeVersionChecksum")
    public JAXBElement<RemoveVersionChecksum> createRemoveVersionChecksum(RemoveVersionChecksum value) {
        return new JAXBElement<RemoveVersionChecksum>(_RemoveVersionChecksum_QNAME, RemoveVersionChecksum.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCertificateByDeviceIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getCertificateByDeviceIdResponse")
    public JAXBElement<GetCertificateByDeviceIdResponse> createGetCertificateByDeviceIdResponse(GetCertificateByDeviceIdResponse value) {
        return new JAXBElement<GetCertificateByDeviceIdResponse>(_GetCertificateByDeviceIdResponse_QNAME, GetCertificateByDeviceIdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateUserCertificateResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "createUserCertificateResponse")
    public JAXBElement<CreateUserCertificateResponse> createCreateUserCertificateResponse(CreateUserCertificateResponse value) {
        return new JAXBElement<CreateUserCertificateResponse>(_CreateUserCertificateResponse_QNAME, CreateUserCertificateResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResetPin }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "resetPin")
    public JAXBElement<ResetPin> createResetPin(ResetPin value) {
        return new JAXBElement<ResetPin>(_ResetPin_QNAME, ResetPin.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnlockDeviceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "unlockDeviceResponse")
    public JAXBElement<UnlockDeviceResponse> createUnlockDeviceResponse(UnlockDeviceResponse value) {
        return new JAXBElement<UnlockDeviceResponse>(_UnlockDeviceResponse_QNAME, UnlockDeviceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LockUser }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "lockUser")
    public JAXBElement<LockUser> createLockUser(LockUser value) {
        return new JAXBElement<LockUser>(_LockUser_QNAME, LockUser.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveDeviceEx }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "removeDeviceEx")
    public JAXBElement<RemoveDeviceEx> createRemoveDeviceEx(RemoveDeviceEx value) {
        return new JAXBElement<RemoveDeviceEx>(_RemoveDeviceEx_QNAME, RemoveDeviceEx.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddGroup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "addGroup")
    public JAXBElement<AddGroup> createAddGroup(AddGroup value) {
        return new JAXBElement<AddGroup>(_AddGroup_QNAME, AddGroup.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CreateActivationCodeEx }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "createActivationCodeEx")
    public JAXBElement<CreateActivationCodeEx> createCreateActivationCodeEx(CreateActivationCodeEx value) {
        return new JAXBElement<CreateActivationCodeEx>(_CreateActivationCodeEx_QNAME, CreateActivationCodeEx.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetReportingItemsResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getReportingItemsResponse")
    public JAXBElement<GetReportingItemsResponse> createGetReportingItemsResponse(GetReportingItemsResponse value) {
        return new JAXBElement<GetReportingItemsResponse>(_GetReportingItemsResponse_QNAME, GetReportingItemsResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddUserResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "addUserResponse")
    public JAXBElement<AddUserResponse> createAddUserResponse(AddUserResponse value) {
        return new JAXBElement<AddUserResponse>(_AddUserResponse_QNAME, AddUserResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link EditVersion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "editVersion")
    public JAXBElement<EditVersion> createEditVersion(EditVersion value) {
        return new JAXBElement<EditVersion>(_EditVersion_QNAME, EditVersion.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StoreTextResources }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "storeTextResources")
    public JAXBElement<StoreTextResources> createStoreTextResources(StoreTextResources value) {
        return new JAXBElement<StoreTextResources>(_StoreTextResources_QNAME, StoreTextResources.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LockDeviceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "lockDeviceResponse")
    public JAXBElement<LockDeviceResponse> createLockDeviceResponse(LockDeviceResponse value) {
        return new JAXBElement<LockDeviceResponse>(_LockDeviceResponse_QNAME, LockDeviceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetPin }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "setPin")
    public JAXBElement<SetPin> createSetPin(SetPin value) {
        return new JAXBElement<SetPin>(_SetPin_QNAME, SetPin.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AssignGroupToUser }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "assignGroupToUser")
    public JAXBElement<AssignGroupToUser> createAssignGroupToUser(AssignGroupToUser value) {
        return new JAXBElement<AssignGroupToUser>(_AssignGroupToUser_QNAME, AssignGroupToUser.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AssignVersionUpdate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "assignVersionUpdate")
    public JAXBElement<AssignVersionUpdate> createAssignVersionUpdate(AssignVersionUpdate value) {
        return new JAXBElement<AssignVersionUpdate>(_AssignVersionUpdate_QNAME, AssignVersionUpdate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveAllActivationCodesResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "removeAllActivationCodesResponse")
    public JAXBElement<RemoveAllActivationCodesResponse> createRemoveAllActivationCodesResponse(RemoveAllActivationCodesResponse value) {
        return new JAXBElement<RemoveAllActivationCodesResponse>(_RemoveAllActivationCodesResponse_QNAME, RemoveAllActivationCodesResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SetPinResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "setPinResponse")
    public JAXBElement<SetPinResponse> createSetPinResponse(SetPinResponse value) {
        return new JAXBElement<SetPinResponse>(_SetPinResponse_QNAME, SetPinResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetCertificate }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getCertificate")
    public JAXBElement<GetCertificate> createGetCertificate(GetCertificate value) {
        return new JAXBElement<GetCertificate>(_GetCertificate_QNAME, GetCertificate.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddVersionResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "addVersionResponse")
    public JAXBElement<AddVersionResponse> createAddVersionResponse(AddVersionResponse value) {
        return new JAXBElement<AddVersionResponse>(_AddVersionResponse_QNAME, AddVersionResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResetPinResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "resetPinResponse")
    public JAXBElement<ResetPinResponse> createResetPinResponse(ResetPinResponse value) {
        return new JAXBElement<ResetPinResponse>(_ResetPinResponse_QNAME, ResetPinResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveDevice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "removeDevice")
    public JAXBElement<RemoveDevice> createRemoveDevice(RemoveDevice value) {
        return new JAXBElement<RemoveDevice>(_RemoveDevice_QNAME, RemoveDevice.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetTextResources }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getTextResources")
    public JAXBElement<GetTextResources> createGetTextResources(GetTextResources value) {
        return new JAXBElement<GetTextResources>(_GetTextResources_QNAME, GetTextResources.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LockDeviceByDeviceId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "lockDeviceByDeviceId")
    public JAXBElement<LockDeviceByDeviceId> createLockDeviceByDeviceId(LockDeviceByDeviceId value) {
        return new JAXBElement<LockDeviceByDeviceId>(_LockDeviceByDeviceId_QNAME, LockDeviceByDeviceId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveDeviceByDeviceIdResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "removeDeviceByDeviceIdResponse")
    public JAXBElement<RemoveDeviceByDeviceIdResponse> createRemoveDeviceByDeviceIdResponse(RemoveDeviceByDeviceIdResponse value) {
        return new JAXBElement<RemoveDeviceByDeviceIdResponse>(_RemoveDeviceByDeviceIdResponse_QNAME, RemoveDeviceByDeviceIdResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ModifyGroup }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "modifyGroup")
    public JAXBElement<ModifyGroup> createModifyGroup(ModifyGroup value) {
        return new JAXBElement<ModifyGroup>(_ModifyGroup_QNAME, ModifyGroup.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddVersion }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "addVersion")
    public JAXBElement<AddVersion> createAddVersion(AddVersion value) {
        return new JAXBElement<AddVersion>(_AddVersion_QNAME, AddVersion.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetStatistic }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getStatistic")
    public JAXBElement<GetStatistic> createGetStatistic(GetStatistic value) {
        return new JAXBElement<GetStatistic>(_GetStatistic_QNAME, GetStatistic.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveDeviceResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "removeDeviceResponse")
    public JAXBElement<RemoveDeviceResponse> createRemoveDeviceResponse(RemoveDeviceResponse value) {
        return new JAXBElement<RemoveDeviceResponse>(_RemoveDeviceResponse_QNAME, RemoveDeviceResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnassignGroupFromUser }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "unassignGroupFromUser")
    public JAXBElement<UnassignGroupFromUser> createUnassignGroupFromUser(UnassignGroupFromUser value) {
        return new JAXBElement<UnassignGroupFromUser>(_UnassignGroupFromUser_QNAME, UnassignGroupFromUser.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link GetReportingItems }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "getReportingItems")
    public JAXBElement<GetReportingItems> createGetReportingItems(GetReportingItems value) {
        return new JAXBElement<GetReportingItems>(_GetReportingItems_QNAME, GetReportingItems.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RemoveDeviceByDeviceId }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.asm.ssms.kobil.com/", name = "removeDeviceByDeviceId")
    public JAXBElement<RemoveDeviceByDeviceId> createRemoveDeviceByDeviceId(RemoveDeviceByDeviceId value) {
        return new JAXBElement<RemoveDeviceByDeviceId>(_RemoveDeviceByDeviceId_QNAME, RemoveDeviceByDeviceId.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "return", scope = GetCertificateResponse.class)
    public JAXBElement<byte[]> createGetCertificateResponseReturn(byte[] value) {
        return new JAXBElement<byte[]>(_GetCertificateResponseReturn_QNAME, byte[].class, GetCertificateResponse.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "return", scope = GetCertificateByDeviceIdResponse.class)
    public JAXBElement<byte[]> createGetCertificateByDeviceIdResponseReturn(byte[] value) {
        return new JAXBElement<byte[]>(_GetCertificateResponseReturn_QNAME, byte[].class, GetCertificateByDeviceIdResponse.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "return", scope = CreateUserCertificateResponse.class)
    public JAXBElement<byte[]> createCreateUserCertificateResponseReturn(byte[] value) {
        return new JAXBElement<byte[]>(_GetCertificateResponseReturn_QNAME, byte[].class, CreateUserCertificateResponse.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "return", scope = CreateAppBundleResponse.class)
    public JAXBElement<byte[]> createCreateAppBundleResponseReturn(byte[] value) {
        return new JAXBElement<byte[]>(_GetCertificateResponseReturn_QNAME, byte[].class, CreateAppBundleResponse.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "return", scope = GetTextResourcesResponse.class)
    public JAXBElement<byte[]> createGetTextResourcesResponseReturn(byte[] value) {
        return new JAXBElement<byte[]>(_GetCertificateResponseReturn_QNAME, byte[].class, GetTextResourcesResponse.class, ((byte[]) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link byte[]}{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "contents", scope = StoreTextResources.class)
    public JAXBElement<byte[]> createStoreTextResourcesContents(byte[] value) {
        return new JAXBElement<byte[]>(_StoreTextResourcesContents_QNAME, byte[].class, StoreTextResources.class, ((byte[]) value));
    }

}
