//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.08.05 at 08:30:26 AM EET 
//


package com.kobil.ssms.asm.ws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for versionParam complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="versionParam">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="allowedToRegisterAppDigestUser" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="appName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="clientType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="deviceType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="downloadUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="informationUrl" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="installer" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="locked" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="softwareType" type="{http://ws.asm.ssms.kobil.com/}softwareTypes" minOccurs="0"/>
 *         &lt;element name="testApp" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="versionStr" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "versionParam", propOrder = {
    "allowedToRegisterAppDigestUser",
    "appName",
    "clientType",
    "deviceType",
    "downloadUrl",
    "informationUrl",
    "installer",
    "locked",
    "softwareType",
    "testApp",
    "versionStr"
})
public class VersionParam {

    protected String allowedToRegisterAppDigestUser;
    protected String appName;
    protected String clientType;
    protected String deviceType;
    protected String downloadUrl;
    protected String informationUrl;
    protected byte[] installer;
    protected boolean locked;
    protected SoftwareTypes softwareType;
    protected boolean testApp;
    protected String versionStr;

    /**
     * Gets the value of the allowedToRegisterAppDigestUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAllowedToRegisterAppDigestUser() {
        return allowedToRegisterAppDigestUser;
    }

    /**
     * Sets the value of the allowedToRegisterAppDigestUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAllowedToRegisterAppDigestUser(String value) {
        this.allowedToRegisterAppDigestUser = value;
    }

    /**
     * Gets the value of the appName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppName() {
        return appName;
    }

    /**
     * Sets the value of the appName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppName(String value) {
        this.appName = value;
    }

    /**
     * Gets the value of the clientType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClientType() {
        return clientType;
    }

    /**
     * Sets the value of the clientType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClientType(String value) {
        this.clientType = value;
    }

    /**
     * Gets the value of the deviceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeviceType() {
        return deviceType;
    }

    /**
     * Sets the value of the deviceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeviceType(String value) {
        this.deviceType = value;
    }

    /**
     * Gets the value of the downloadUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDownloadUrl() {
        return downloadUrl;
    }

    /**
     * Sets the value of the downloadUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDownloadUrl(String value) {
        this.downloadUrl = value;
    }

    /**
     * Gets the value of the informationUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInformationUrl() {
        return informationUrl;
    }

    /**
     * Sets the value of the informationUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInformationUrl(String value) {
        this.informationUrl = value;
    }

    /**
     * Gets the value of the installer property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getInstaller() {
        return installer;
    }

    /**
     * Sets the value of the installer property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setInstaller(byte[] value) {
        this.installer = value;
    }

    /**
     * Gets the value of the locked property.
     * 
     */
    public boolean isLocked() {
        return locked;
    }

    /**
     * Sets the value of the locked property.
     * 
     */
    public void setLocked(boolean value) {
        this.locked = value;
    }

    /**
     * Gets the value of the softwareType property.
     * 
     * @return
     *     possible object is
     *     {@link SoftwareTypes }
     *     
     */
    public SoftwareTypes getSoftwareType() {
        return softwareType;
    }

    /**
     * Sets the value of the softwareType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SoftwareTypes }
     *     
     */
    public void setSoftwareType(SoftwareTypes value) {
        this.softwareType = value;
    }

    /**
     * Gets the value of the testApp property.
     * 
     */
    public boolean isTestApp() {
        return testApp;
    }

    /**
     * Sets the value of the testApp property.
     * 
     */
    public void setTestApp(boolean value) {
        this.testApp = value;
    }

    /**
     * Gets the value of the versionStr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersionStr() {
        return versionStr;
    }

    /**
     * Sets the value of the versionStr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersionStr(String value) {
        this.versionStr = value;
    }

}
